# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86eb79d72e0c74e1d9238c40500d81dc6ef01e44c2e1f7d57ff389959b2cd648a78b1d08c16affcf0734c354a9d56ba1052277e4b9998ebb7861a27ec207f0fc

test:
  secret_key_base: 0b7fb87acff1a1b27b70b3d705c7ec93b925d1887ac1c05e9d4a4de4bee8f7cbfeb6ae011f95b0ccdb0c02f83fb210561f524b400b10b855e7f8182b4b9b9dba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
